apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 27.3.1
      helm:
        releaseName: prometheus
        valuesFiles: 
          - $values/prometheus/values.yaml
    - repoURL: https://github.com/Layzan/web-page-deploy.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: monitoramento
    server: https://kubernetes.default.svc

