apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.3.1
    helm:
      releaseName: prometheus
  destination:
    namespace: monitoramento
    server: https://kubernetes.default.svc
  info:
    - name: Projeto
      value: "Curso de GitOps"
